#ifndef INC_HMLIB_STANDARDTYPE
#define INC_HMLIB_STANDARDTYPE 100
#define TYPE_SIZE_CHAR 1
#define TYPE_SIZE_SHORT 2
#define TYPE_SIZE_INT 4
#define TYPE_SIZE_LONG 4
#define TYPE_SIZE_LONG_LONG 8
#define TYPE_SIZE_FLOAT 4
#define TYPE_SIZE_DOUBLE 8
#define TYPE_SIZE_LONG_DOUBLE 8
#endif
